version: '3.4'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  crawler:
    build: .
    network_mode: host
    restart: always
    environment: 
      - KAFKA_HOST=localhost:9092
      - KAFKA_AGODA_TOPIC=agoda_crawler
      - KAFKA_FINDHOTELS_TOPIC=findhotesl_crawler
      - KAFKA_CONSUMER_GROUP=CrawlerGroup
      - MONGO_CONNECTION_STRING=mongodb://localhost:27017
      - MONGO_DB_NAME=Hotels
    depends_on: 
      - kafka
      - mongo

  